name: Go

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install
      run: go build ./...
      
    - name: ls
      run: ls
      
    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mqtt_*
        file_glob: true
        tag: "test1"
        prerelease: true
        overwrite: true
